version: '3.7'

services:
    ts-node-docker:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        env_file:
            - .env-docker
        volumes:
            - ./src:/home/node/app/src
            - ./nodemon.json:/home/node/app/nodemon.json
        container_name: bird-identifier-backend
        expose:
            - '4000'
        ports:
            - '4000:4000'
        command: npm run dev

    db:
        image: postgres:latest
        ports:
            - 5432:5432
        restart: always
        environment:
            POSTGRES_PASSWORD: Bostick732
            POSTGRES_USER: bird
            POSTGRES_DB: bird-db
        container_name: bird-db-container
        volumes:
            - ~/apps/postgres:/var/lib/postgresql/data
            - ./data/birds.csv:/docker-entrypoint-initdb.d/birds.csv
            - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
